### ISSUE TITLE
US 01.01.01 - Create the OwnedIngredient class

### ISSUE THREAD

**Issue by ethanfranz7** [CMPUT301F22T15/Foodverse#14]
As a meal planner, I want to add an ingredient, with a brief description, best before date, location, amount, unit, and ingredient category

- [x] Create class for ingredients
- [x] Create interface for adding ingredients

**Comment by Ppatel122** [comment]
Should we add the best before date and location of the ingredient to the CRC card?

**Comment by tylers-ualberta** [comment]
I've modified the locations field to draw values from an XML string array rather than an enum to make Firebase integration smoother. See [commit d8e64cf](https://github.com/CMPUT301F22T15/Foodverse/commit/d8e64cf82cb5d3b56735e615b077efceb4c0948e) and [commit 0d4648a](https://github.com/CMPUT301F22T15/Foodverse/commit/0d4648a266cd849f99faaf5e97b7ecfbfa074620)
